spring:
  datasource:
    url: ${MASTER_DB_URL}
    username: ${MASTER_USERNAME}
    password: ${MASTER_PASSWORD}

security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
