spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}

security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
